import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  sectionTitle: { fontSize: 20, fontWeight: 'bold', color: '#1D3D47', marginBottom: 15, marginTop: 25 },
  emptyText: { textAlign: 'center', color: '#666', marginTop: 20, padding: 20, width: '100%' },
  walletsCarousel: { paddingHorizontal: 2, paddingBottom: 10 },
  walletCard: {
    backgroundColor: 'white',
    borderRadius: 15,
    padding: 15,
    width: 180,
    marginRight: 15,
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 3,
  },
  walletCardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  walletCardName: { fontSize: 16, fontWeight: 'bold', color: '#1D3D47' },
  walletCardCurrency: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFF',
    backgroundColor: '#007AFF',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    overflow: 'hidden',
  },
  walletCardBalance: { fontSize: 22, fontWeight: 'bold', color: '#1D3D47', marginVertical: 10 },
  walletCardActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10 },
  walletButton: { width: 36, height: 36, borderRadius: 18, justifyContent: 'center', alignItems: 'center' },
  incomeButton: { backgroundColor: '#28a745' },
  expenseButton: { backgroundColor: '#dc3545' },
});
