import { StyleSheet } from 'react-native';
import { ColorTheme } from '../types';

export const getStyles = (colors: ColorTheme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      paddingTop: 50,
      paddingHorizontal: 20,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.background,
    },
    timeRangeContainer: {
      flexDirection: 'row',
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 4,
      borderWidth: 1,
      borderColor: colors.border,
    },
    timeRangeButton: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 8,
    },
    timeRangeButtonSelected: {
      backgroundColor: colors.primary,
    },
    timeRangeButtonText: {
      color: colors.text,
      opacity: 0.6,
      fontWeight: '600',
      fontSize: 12,
    },
    timeRangeButtonTextSelected: {
      color: 'white',
      fontWeight: 'bold',
      fontSize: 12,
    },
    scrollView: {
      flex: 1,
    },
    summaryGrid: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 12,
    },
    miniCard: {
      flex: 1,
      backgroundColor: colors.card,
      padding: 16,
      borderRadius: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
      borderWidth: 1,
      borderColor: colors.border,
    },
    miniCardTitle: {
      fontSize: 12,
      color: colors.text,
      opacity: 0.6,
      marginBottom: 4,
    },
    miniCardAmount: {
      fontSize: 18,
      fontWeight: 'bold',
    },
    mainCard: {
      backgroundColor: colors.card,
      padding: 20,
      borderRadius: 16,
      alignItems: 'center',
      marginBottom: 24,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 4,
      borderWidth: 1,
      borderColor: colors.border,
    },
    summaryTitle: {
      fontSize: 14,
      color: colors.text,
      opacity: 0.7,
      marginBottom: 4,
    },
    summaryAmount: {
      fontSize: 28,
      fontWeight: 'bold',
      color: colors.notification,
    },
    incomeAmount: {
      fontSize: 28,
      fontWeight: 'bold',
      color: colors.primary,
    },
    netFlowAmountPositive: {
      fontSize: 32,
      fontWeight: 'bold',
      color: '#28a745',
    },
    netFlowAmountNegative: {
      fontSize: 32,
      fontWeight: 'bold',
      color: colors.notification,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: colors.text,
      marginBottom: 12,
    },
    chartCard: {
      backgroundColor: colors.card,
      padding: 10,
      borderRadius: 16,
      marginBottom: 24,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    categoryItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: colors.card,
      padding: 15,
      borderRadius: 12,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    categoryIndicator: {
      width: 12,
      height: 12,
      borderRadius: 6,
      marginRight: 10,
    },
    categoryName: {
      fontSize: 15,
      color: colors.text,
    },
    categoryAmount: {
      fontSize: 15,
      fontWeight: 'bold',
      color: colors.text,
    },
    emptyText: {
      textAlign: 'center',
      marginTop: 20,
      color: colors.text,
      opacity: 0.6,
      fontStyle: 'italic',
    },
  });
