import { StyleSheet } from 'react-native';

export const getStyles = (colors: any) =>
  StyleSheet.create({
    modalContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
      width: '85%',
      maxHeight: '80%',
      padding: 20,
      backgroundColor: colors.card,
      borderRadius: 10,
      alignItems: 'center',
    },
    modalTitle: { fontSize: 20, fontWeight: 'bold', marginBottom: 20, textAlign: 'center', color: colors.text },
    currencySelector: {
      flexDirection: 'row',
      width: '100%',
      borderWidth: 1,
      borderColor: colors.primary,
      borderRadius: 10,
      overflow: 'hidden',
      marginBottom: 15,
    },
    currencyOption: { flex: 1, paddingVertical: 10, alignItems: 'center', backgroundColor: colors.background },
    currencyOptionSelected: { backgroundColor: colors.primary },
    currencyText: { fontSize: 16, color: colors.primary },
    currencyTextSelected: { color: colors.card, fontWeight: 'bold' },
    buttonContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      width: '100%',
      marginTop: 20,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    pickerLabel: {
      fontSize: 16,
      color: colors.text,
      opacity: 0.8,
      marginBottom: 10,
      alignSelf: 'flex-start',
    },
    categoryItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.primary,
      marginRight: 8,
      backgroundColor: colors.background,
    },
    categoryItemSelected: { backgroundColor: colors.primary },
    categoryItemText: { color: colors.primary, fontSize: 14 },
    categoryItemTextSelected: { color: colors.card, fontWeight: 'bold' },
  });
